Add support for oracular/v19
jidicula/clang-format-action pull request #221
Opened 2024-10-28 10:12 UTC by RichLogan

2024-11-27 12:12 UTC, jidicula requested changes
Hey, thanks for your contribution! This needs to be broken into 2 PRs, like I did for https://github.com/jidicula/clang-format-action/pull/182 and https://github.com/jidicula/clang-format-action/pull/183 - in the first PR, we add the new image to the autobuilds that are published to ghcr.io, then the 2nd PR references that image once it's published.


If you're not able to address those requested changes by the weekend, don't worry about it and I'll make them myself and add you as co-author on them 🙂.

2024-11-27 14:16 UTC, RichLogan commented
@jidicula Thanks, will do!

2024-11-27 16:11 UTC, jidicula approved these changes

2024-11-27 19:28 UTC, merged

2024-11-28 08:56 UTC, jidicula commented
@RichLogan I've approved and merged! Whenever you're ready, you can submit the 2nd PR 🙂